#!/bin/bash

echo " ##### Looking for USB drive ##### "
if [ $(find /media/pi -mindepth 1 -maxdepth 1 -type d | wc -l) -eq 0 ]
then
  echo "Insert USB drive with your wallet.dat"
  echo "Installation will continue in the meantime, but will require it later"
fi

echo " ##### Installing dependencies ##### "
sudo aptitude update
sudo aptitude -y install python-pip python-smbus libminiupnpc-dev libqt4-dev Xvfb x11vnc expect i2c-tools
sudo pip install daemonize gpio python-bitcoinrpc python-daemon
sudo update-rc.d -f lightdm remove

echo " ##### Downloading TrezarPi ##### "
sudo rm -rf /usr/share/trezarpi/
sudo rm -rf trezarpi.tar.gz
wget https://github.com/mkapusnik/gpio/releases/download/tzc/trezarpi.tar.gz

echo " ##### Extracting TrezarPi ##### "
sudo tar -C / -xzf trezarpi.tar.gz

echo " ##### Installing services into the OS ##### "
sudo su -c '. raspi-config nonint && do_i2c 0'
#sudo su -c '. raspi-config nonint && do_boot_behaviour B1 B1'
echo 'trezarpi' | sudo tee /etc/hostname > /dev/null

chmod +x /usr/bin/trezarcoin-qt
sudo chown root:root /etc/rc.local
sudo chmod 755 /etc/rc.local

echo " ##### Setting up autostart ##### "
#sudo nano /etc/trezarpi.conf

# TODO
echo " ##### Initializing USB drive ##### "
while [ $(find /media/pi -mindepth 1 -maxdepth 1 -type d | wc -l) -eq 0 ]; do echo "Insert USB drive ..." && sleep 5; done
dir=$(find /media/pi -mindepth 1 -maxdepth 1 -type d)
cp -n /etc/trezarpi.conf $dir

echo " ##### Rebooting ##### "
sudo reboot