#!/usr/bin/expect
target=$1
password=$2

/usr/share/trezarpi/lcd Backup Started

dir=$(find /media/pi -mindepth 1 -maxdepth 1 -type d)
spawn rsync -av -e ssh $dir $target
expect "password:"
send "${password}\n"
expect eof
if [catch wait] {
    puts "rsync failed"
    exit 1
}
/usr/share/trezarpi/lcd Backup Done
exit 0