#!/bin/bash
echo " ##### Downloading updates ##### "
sudo rm -rf update.tar.gz
wget https://github.com/mkapusnik/gpio/releases/download/tzc/update.tar.gz

echo " ##### Installing updates ##### "
sudo tar -C / -xzf update.tar.gz

echo " ##### Rebooting ##### "
sudo reboot